# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      discussions: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven1
      run: mvn clean verify -f releng/plugins/org.polarsys.capella.studio.releng.targets/pom.xml

    - name: Build with Maven
      run: mvn clean verify -P full -P product

    - name: echo log
      run: ls -l ./releng/plugins/org.polarsys.capella.studio.releng.product/target/products

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./releng/plugins/org.polarsys.capella.studio.releng.product/target/products/capella-studio-*.zip
